site_name: eVTOL BFSM documentation

# Описание сайта. Добавляется в meta в html-заголовке каждой страницы.
site_description: Project documentation for eVTOL BFSM.

site_url: https://ssavchuk.github.io/evtol-bfsm

# site_url: https://www.mkdocs.org/

site_author: BFSM Team

repo_url: https://github.com/ssavchuk/evtol-bfsm

nav:
  - Home: index.md
  - Блог:
    - blog/index.md
  - Летаки:
    - BFSM: drones/BFSM/BFSM.md
    - Чемодан: drones/suitcase/suitcase.md
    - Куб: drones/cube/cube.md
  - Настройки:
    - Оборудование:
      - GPS:
        - NEO 3 Pro GPS: settings/equipment/GPS/NEO_3_Pro_GPS.md
      - Дисплеи: settings/equipment/display.md
      - PX4FLOW: settings/equipment/PX4FLOW.md
      - Lidar C1 360: settings/equipment/Lidar_C1_360.md
      - Range Finder Istra24: settings/equipment/Range_Finder_Istra24.md
    - Подключение:
      - wifi: settings/wifi.md
    - Параметры: settings/parameters.md
    - Initial Tune Params: settings/initial_tune_params.md
    - Настрока компаса: settings/compass.md
    - PID: settings/PID/PID.md
    - Режимы полётов: settings/flight_modes.md
    - Автовзлёт: settings/takeoff.md
    - Компенсация горизонта: settings/horizon_compensation.md
    - Журнал: settings/log.md
    - Миссии: settings/mission_commands.md
    - ВМГ: settings/vmg.md
    - EKF: settings/EKF.md
    - Прошивки: settings/firmware.md
  - Оборудование:
    - Моторы:
      - 25KW MP 120100 Outrunner Brushless Motor: equipment\motors\25KW_MP_120100_Outrunner_Brushless_Motor\MP120100.md
    - Радары и лидары:
      - Radar ISTRA24: equipment\lidar_radar\radar_istra24\istra24.md
      - RPLidar C1: equipment\lidar_radar\RPLidar_C1\RPLidarC1.md
    - Модули питания:
      - APM Pixhawk Power Module: equipment\PM\APM_Pixhawk_Power_Module\APM_Pixhawk_Power_Module.md
    - BMS: equipment\bms.md
  - Теория:
    - PID:
      - Что такое PID, на что влияет и как настроить: theory/pid/chto-takoe-pid-na-chto-vliyaet-i-kak-nastroit/chto-takoe-pid-na-chto-vliyaet-i-kak-nastroit.md
    - IMU: theory/IMU.md
    - EKF: theory/EKF.md
    - MAVLink: theory/MAVLink.md
    - Питание (аккумуляторы): theory/power.md
    - ESC: theory/esc.md
    - PPM: theory/PPM.md
    - Термины: theory/terms.md
  - Руководства: manuals/manuals.md
  - Книги: books/books.md
  - Разное:
    - Список для полевых исспытаний: misc/field_tests_checklist.md
    - Roadmap: misc/roadmap.md

markdown_extensions:
  - markdown.extensions.nl2br
  - attr_list

# theme: material
# theme: bootstrap4
# theme: readthedocs

theme:
  name: material
  custom_dir: overrides
  language: ru-custom
  features:
    - content.code.copy
    - tabs
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
  - search:
      lang: ["ru", "en"]
  # - i18n:
  #     docs_structure: suffix
  #     languages:
  #       - locale: ru
  #         name: Russian
  #         default: true
  #         build: true
  #         site_name: "Документация для проекта eVTOL BFSM"
  - blog:
      post_url_format: "{date}/{file}"
      categories: false
      blog_toc: true
      archive: false
      post_readtime_words_per_minute: 250
      pagination: false
  # - blog:
  #     enabled: true
  #     blog_dir: blog
  #     post_url_format: "{date}/{file}"
  #     post_dir: "{blog}/posts"
  #     categories: false
  #     blog_toc: true
  #     archive: false
  #     post_readtime_words_per_minute: 250
  #     pagination: false

validation:
  links:
    absolute_links: relative_to_docs
    anchors: warn
    unrecognized_links: warn
